/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsHandleRouteImport } from './routes/products.$handle'
import { Route as PagesFaqRouteImport } from './routes/pages.faq'
import { Route as PagesContactRouteImport } from './routes/pages.contact'
import { Route as CollectionsMaterialRouteImport } from './routes/collections.$material'

const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHandleRoute = ProductsHandleRouteImport.update({
  id: '/products/$handle',
  path: '/products/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesFaqRoute = PagesFaqRouteImport.update({
  id: '/pages/faq',
  path: '/pages/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesContactRoute = PagesContactRouteImport.update({
  id: '/pages/contact',
  path: '/pages/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsMaterialRoute = CollectionsMaterialRouteImport.update({
  id: '/collections/$material',
  path: '/collections/$material',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/cart': typeof CartRoute
  '/collections/$material': typeof CollectionsMaterialRoute
  '/pages/contact': typeof PagesContactRoute
  '/pages/faq': typeof PagesFaqRoute
  '/products/$handle': typeof ProductsHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/cart': typeof CartRoute
  '/collections/$material': typeof CollectionsMaterialRoute
  '/pages/contact': typeof PagesContactRoute
  '/pages/faq': typeof PagesFaqRoute
  '/products/$handle': typeof ProductsHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/cart': typeof CartRoute
  '/collections/$material': typeof CollectionsMaterialRoute
  '/pages/contact': typeof PagesContactRoute
  '/pages/faq': typeof PagesFaqRoute
  '/products/$handle': typeof ProductsHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brands'
    | '/cart'
    | '/collections/$material'
    | '/pages/contact'
    | '/pages/faq'
    | '/products/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brands'
    | '/cart'
    | '/collections/$material'
    | '/pages/contact'
    | '/pages/faq'
    | '/products/$handle'
  id:
    | '__root__'
    | '/'
    | '/brands'
    | '/cart'
    | '/collections/$material'
    | '/pages/contact'
    | '/pages/faq'
    | '/products/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandsRoute: typeof BrandsRoute
  CartRoute: typeof CartRoute
  CollectionsMaterialRoute: typeof CollectionsMaterialRoute
  PagesContactRoute: typeof PagesContactRoute
  PagesFaqRoute: typeof PagesFaqRoute
  ProductsHandleRoute: typeof ProductsHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$handle': {
      id: '/products/$handle'
      path: '/products/$handle'
      fullPath: '/products/$handle'
      preLoaderRoute: typeof ProductsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/faq': {
      id: '/pages/faq'
      path: '/pages/faq'
      fullPath: '/pages/faq'
      preLoaderRoute: typeof PagesFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/contact': {
      id: '/pages/contact'
      path: '/pages/contact'
      fullPath: '/pages/contact'
      preLoaderRoute: typeof PagesContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$material': {
      id: '/collections/$material'
      path: '/collections/$material'
      fullPath: '/collections/$material'
      preLoaderRoute: typeof CollectionsMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandsRoute: BrandsRoute,
  CartRoute: CartRoute,
  CollectionsMaterialRoute: CollectionsMaterialRoute,
  PagesContactRoute: PagesContactRoute,
  PagesFaqRoute: PagesFaqRoute,
  ProductsHandleRoute: ProductsHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
